import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      // eslint-config-next 16.2.12 widened these React Compiler rules' detection,
      // flagging 31 pre-existing sites (settings-form "mirror org state into local
      // state" pattern, SessionForm ref reads). Keep visible as warnings; fix sites
      // incrementally rather than churning every settings page + the session form
      // in a deps bump.
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/refs": "warn",
      "react-hooks/preserve-manual-memoization": "warn",
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Utility scripts (Node.js CommonJS)
    "scripts/**",
    // Generated by `supabase start` — vendored edge-runtime source we neither
    // author nor ship. Linting it added 154 errors (prefer-const, no-var) the
    // moment the local stack was first started.
    "supabase/.temp/**",
    // Nested app folder (separate project copy)
    "mca-app/**",
    // Test-runner outputs (created on failing runs) and walkthrough-audit results.
    "playwright-report/**",
    "test-results/**",
    ".walkthrough-audit/**",
    // Vendored agent tooling (skills ship their own minified scripts) — not app source.
    ".agents/**",
    ".claude/**",
    ".codex/**",
  ]),
]);

export default eslintConfig;
