import type { Walkthrough } from '../walkthrough-types'

export const APP_OVERVIEW_WALKTHROUGH: Walkthrough = {
  id: 'app-overview',
  name: 'App Overview',
  description: 'Learn the basics of navigating MCA Manager',
  steps: [
    {
      title: 'Welcome to the Dashboard',
      description: 'This is your home base. The stats grid gives you a quick snapshot of sessions this month, total clients, pending invoices, and outstanding amounts.',
      element: '[data-tour="dashboard-stats"]',
      popoverSide: 'bottom',
      ctaLabel: 'Next',
      href: '/dashboard/',
    },
    {
      title: 'Action Center',
      description: 'Below the stats you\'ll find action items that need attention — pending approvals, unbilled sessions, unsent invoices, and overdue invoices. Address these to keep your practice running smoothly.',
      element: '[data-tour="dashboard-action-center"]',
      popoverSide: 'top',
      ctaLabel: 'Next',
      href: '/dashboard/',
    },
    {
      title: 'Recent Sessions',
      description: 'A quick view of the latest session entries. Click any session to see its full details, or click "View all sessions" to go to the Sessions page.',
      element: '[data-tour="dashboard-recent-sessions"]',
      popoverSide: 'top',
      ctaLabel: 'Next',
      href: '/dashboard/',
    },
    {
      title: 'Sessions',
      description: 'The Sessions page is where you log therapy sessions, track their status, and manage approvals. Use the sort and filter controls to find what you need.',
      element: 'nav a[href="/sessions/"]',
      popoverSide: 'right',
      ctaLabel: 'Next',
      href: '/dashboard/',
    },
    {
      title: 'Clients',
      description: 'Manage your client list, contact info, and payment methods. Each client\'s payment method determines how their invoices are generated.',
      element: 'nav a[href="/clients/"]',
      popoverSide: 'right',
      ctaLabel: 'Next',
      href: '/dashboard/',
    },
    {
      title: 'Invoices',
      description: 'View and manage all invoices. Track pending, sent, paid, and overdue invoices. Scholarship billing has its own tab for monthly batch invoicing.',
      element: 'nav a[href="/invoices/"]',
      popoverSide: 'right',
      ctaLabel: 'Next',
      href: '/dashboard/',
    },
    {
      title: 'Settings',
      description: 'Configure service types, pricing, team invites, branding, automation, and more. This is where you customize how your practice works.',
      element: 'nav a[href="/settings/"]',
      popoverSide: 'right',
      ctaLabel: 'Finish',
      href: '/dashboard/',
    },
  ],
}

export const ADD_CLIENT_WALKTHROUGH: Walkthrough = {
  id: 'add-client',
  name: 'Add Your First Client',
  description: 'Learn how to add a client to your practice',
  steps: [
    {
      title: 'Navigate to Clients',
      description: 'The Clients page shows all your clients. The stats at the top give you a quick count and flag any clients missing contact info.',
      element: 'nav a[href="/clients/"]',
      popoverSide: 'right',
      ctaLabel: 'Go to Clients',
      href: '/clients/',
    },
    {
      title: 'Your Client List',
      description: 'This table shows all your clients with their contact info and payment method. Click any row to view or edit a client\'s details.',
      element: '[data-tour="clients-table"]',
      popoverSide: 'top',
      ctaLabel: 'Next',
      href: '/clients/',
    },
    {
      title: 'Click Add Client',
      description: 'Click the "Add Client" button to open the form. Fill in the client\'s name, email (optional), phone, and payment method.',
      element: '[data-tour="clients-add-button"]',
      popoverSide: 'bottom',
      ctaLabel: 'Next',
      href: '/clients/',
    },
    {
      title: 'Choose Payment and Billing Methods',
      description: 'Select how this client pays (Private Pay, Self-Directed, Group Home, Scholarship, or Venmo) and how you bill them (Square, Check, Email, or Other). This affects how invoices are generated and tracked.',
      ctaLabel: 'Finish',
      href: '/clients/',
    },
  ],
}

export const LOG_SESSION_WALKTHROUGH: Walkthrough = {
  id: 'log-session',
  name: 'Log a Session',
  description: 'Learn how to log a therapy session',
  steps: [
    {
      title: 'Start a New Session',
      description: 'Navigate to Sessions and click "New Session" to begin. On mobile, you can also use the floating + button at the bottom of the screen.',
      element: '[data-tour="sessions-new-button"]',
      popoverSide: 'bottom',
      ctaLabel: 'Go to New Session',
      href: '/sessions/new/',
    },
    {
      title: 'Date and Time',
      description: 'Set the date and time for the session. The date defaults to today and the time defaults to your last used value.',
      element: '[data-tour="session-form-datetime"]',
      popoverSide: 'bottom',
      ctaLabel: 'Next',
      href: '/sessions/new/',
    },
    {
      title: 'Duration',
      description: 'Choose the session length. This affects pricing — a 60-minute session bills at 2x the 30-minute rate. Your last used duration is remembered.',
      element: '[data-tour="session-form-duration"]',
      popoverSide: 'bottom',
      ctaLabel: 'Next',
      href: '/sessions/new/',
    },
    {
      title: 'Service Type',
      description: 'Choose the service type which determines pricing, contractor pay, and whether a client is required. Your last used service type is remembered.',
      element: '[data-tour="session-form-service-type"]',
      popoverSide: 'bottom',
      ctaLabel: 'Next',
      href: '/sessions/new/',
    },
    {
      title: 'Select Client',
      description: 'Search and select the client(s) who attended. For group services, you can add multiple clients. Some services like admin work skip this field.',
      element: '[data-tour="session-form-clients"]',
      popoverSide: 'bottom',
      ctaLabel: 'Next',
      href: '/sessions/new/',
    },
    {
      title: 'Session Notes',
      description: 'Add internal notes (only visible to your team) and client notes (visible in the client portal). Notes are encrypted for HIPAA compliance.',
      element: '#notes',
      popoverSide: 'bottom',
      ctaLabel: 'Next',
      href: '/sessions/new/',
    },
    {
      title: 'Submit or Save Draft',
      description: 'Choose "Submit for approval" to send the session for admin review, or "Save as draft" to finish later. After submitting, you can quickly "Log Another" session.',
      element: '[data-tour="session-form-submit"]',
      popoverSide: 'top',
      ctaLabel: 'Finish',
      href: '/sessions/new/',
    },
  ],
}

export const INVITE_CONTRACTOR_WALKTHROUGH: Walkthrough = {
  id: 'invite-contractor',
  name: 'Invite a Contractor',
  description: 'Learn how to invite team members',
  steps: [
    {
      title: 'Go to Team',
      description: 'Team management is in the Team section of the sidebar.',
      element: 'nav a[href="/team/"]',
      popoverSide: 'right',
      ctaLabel: 'Go to Team',
      href: '/team/',
    },
    {
      title: 'Team Summary',
      description: 'The summary cards show total team members, total sessions logged, pending contractor pay, and active contractor count.',
      element: '[data-tour="team-stats"]',
      popoverSide: 'bottom',
      ctaLabel: 'Next',
      href: '/team/',
    },
    {
      title: 'Team Members Table',
      description: 'View all team members with their roles, session counts, and earnings. Use the actions column to manage individual members.',
      element: '[data-tour="team-members-card"]',
      popoverSide: 'top',
      ctaLabel: 'Next',
      href: '/team/',
    },
    {
      title: 'Pay Rate Matrix',
      description: 'Switch to the Rates tab to see a matrix of all contractor pay rates across service types at a glance. You can set custom per-contractor rates here.',
      element: '[data-tour="team-tab-rates"]',
      popoverSide: 'bottom',
      ctaLabel: 'Next',
      href: '/team/',
    },
    {
      title: 'Send an Invite',
      description: 'Click "Invite Team Member", enter their email, and select their role (Contractor, Admin, or Owner). They\'ll receive an email with a link to create their account.',
      element: '[data-tour="team-invite-button"]',
      popoverSide: 'bottom',
      ctaLabel: 'Finish',
      href: '/team/',
    },
  ],
}

export const CONFIGURE_SERVICES_WALKTHROUGH: Walkthrough = {
  id: 'configure-services',
  name: 'Configure Services',
  description: 'Learn how to set up service types and pricing',
  steps: [
    {
      title: 'Go to Settings',
      description: 'Service type configuration is in Settings > Business Rules.',
      element: 'nav a[href="/settings/"]',
      popoverSide: 'right',
      ctaLabel: 'Go to Settings',
      href: '/settings/business/',
    },
    {
      title: 'Service Types List',
      description: 'You\'ll see all your current service types with their pricing. Each card shows the base rate, MCA percentage, and key settings. Click any service type to edit it.',
      ctaLabel: 'Next',
      href: '/settings/business/',
    },
    {
      title: 'Add or Edit a Service',
      description: 'Click "Add Service Type" to create a new one, or click an existing service to edit it. The form lets you set base rate, per-person rate (for groups), contractor cap, total cap, rent, scholarship rate, and more.',
      ctaLabel: 'Next',
      href: '/settings/business/',
    },
    {
      title: 'Detailed Editing Walkthrough',
      description: 'For a step-by-step guide through every field in the service type form, check the "Edit a Service Type" walkthrough in the Help section. It highlights each field and explains what it does.',
      ctaLabel: 'Finish',
      href: '/settings/business/',
    },
  ],
}

export const APPROVE_SESSIONS_WALKTHROUGH: Walkthrough = {
  id: 'approve-sessions',
  name: 'Approve Sessions',
  description: 'Learn how to review and approve submitted sessions',
  steps: [
    {
      title: 'Sessions Page',
      description: 'Go to the Sessions page. Submitted sessions appear with a "Submitted" badge and are waiting for your review.',
      element: 'nav a[href="/sessions/"]',
      popoverSide: 'right',
      ctaLabel: 'Go to Sessions',
      href: '/sessions/',
    },
    {
      title: 'Filter and Search',
      description: 'Use the search bar to find sessions by service type, client, or contractor name. The filter controls let you narrow by status, date range, and contractor.',
      element: '[data-tour="sessions-filters"]',
      popoverSide: 'bottom',
      ctaLabel: 'Next',
      href: '/sessions/',
    },
    {
      title: 'Session List',
      description: 'Each session card shows the date, service type, client, contractor, duration, and status badge. Click a session to view full details including notes and pricing breakdown.',
      element: '[data-tour="sessions-list"]',
      popoverSide: 'top',
      ctaLabel: 'Next',
      href: '/sessions/',
    },
    {
      title: 'Inline Approve',
      description: 'For submitted sessions, you\'ll see an "Approve" button right on the session card. Click it to approve instantly without opening the details page.',
      ctaLabel: 'Next',
      href: '/sessions/',
    },
    {
      title: 'Bulk Approve',
      description: 'Use the "Select all submitted" checkbox at the top of the list to select multiple sessions, then click the "Approve" button in the bulk action bar to approve them all at once.',
      ctaLabel: 'Next',
      href: '/sessions/',
    },
    {
      title: 'Other Actions',
      description: 'From a session\'s detail page, you can also Reject (with a reason), Mark No-Show (charges the no-show fee), or Cancel. Approving auto-generates an invoice for the session.',
      ctaLabel: 'Finish',
      href: '/sessions/',
    },
  ],
}

export const SCHOLARSHIP_BILLING_WALKTHROUGH: Walkthrough = {
  id: 'scholarship-billing',
  name: 'Scholarship Billing',
  description: 'Learn how to generate monthly scholarship invoices',
  steps: [
    {
      title: 'Go to Invoices',
      description: 'Navigate to the Invoices page from the sidebar.',
      element: 'nav a[href="/invoices/"]',
      popoverSide: 'right',
      ctaLabel: 'Go to Invoices',
      href: '/invoices/',
    },
    {
      title: 'Invoice Summary',
      description: 'The summary cards show your pending, awaiting payment, and overdue invoice totals at a glance.',
      element: '[data-tour="invoices-stats"]',
      popoverSide: 'bottom',
      ctaLabel: 'Next',
      href: '/invoices/',
    },
    {
      title: 'Invoice Tabs',
      description: 'Invoices are organized by status — Pending, Sent, Paid, and more. You can also filter by Self-Directed and Group Home payment types.',
      element: '[data-tour="invoices-card"]',
      popoverSide: 'top',
      ctaLabel: 'Next',
      href: '/invoices/',
    },
    {
      title: 'Open the Scholarship Tab',
      description: 'Click the purple "Scholarship" tab to see unbilled scholarship sessions grouped by client and month. This tab only appears for admins.',
      element: '[data-tour="invoices-tab-scholarship"]',
      popoverSide: 'bottom',
      ctaLabel: 'Next',
      href: '/invoices/',
    },
    {
      title: 'Scholarship Content',
      description: 'The Scholarship tab shows unbilled sessions grouped by client and month, existing batch invoices, and unpaid scholarship invoices. Each group has a "Generate Invoice" button.',
      element: '[data-tour="invoices-scholarship-content"]',
      popoverSide: 'top',
      ctaLabel: 'Next',
      href: '/invoices/',
    },
    {
      title: 'Generate Invoices',
      description: 'Click "Generate Invoice" for each client/month group, or "Generate All" to create batch invoices for all unbilled sessions at once. Invoices are created as Pending so you can review before sending.',
      ctaLabel: 'Finish',
      href: '/invoices/',
    },
  ],
}

export const EDIT_SERVICE_TYPE_WALKTHROUGH: Walkthrough = {
  id: 'edit-service-type',
  name: 'Edit a Service Type',
  description: 'Learn how to customize service type pricing, pay, and special behaviors',
  steps: [
    {
      title: 'Go to Settings',
      description: 'Service types are configured under Settings > Business Rules.',
      element: 'nav a[href="/settings/"]',
      ctaLabel: 'Go to Settings',
      href: '/settings/business/',
    },
    {
      title: 'Open a Service Type',
      description: 'We\'ll open the first service type so you can see all the fields. The edit form will appear automatically.',
      ctaLabel: 'Open Form',
      href: '/settings/business/?tour=edit-service',
    },
    {
      title: 'Service Name',
      description: 'The name appears on sessions, invoices, and payroll. Use something descriptive like "In-Home Individual Music Therapy" so contractors pick the right one quickly.',
      element: '#name',
      popoverSide: 'bottom',
      ctaLabel: 'Next',
      href: '/settings/business/?tour=edit-service',
    },
    {
      title: 'Category & Location',
      description: 'Category (Music/Art, Individual/Group) organizes your analytics and reports. Location tracks where the service happens — set it to Matt\'s Music when rent applies.',
      element: '[data-tour="category-location"]',
      popoverSide: 'bottom',
      ctaLabel: 'Next',
      href: '/settings/business/?tour=edit-service',
    },
    {
      title: 'Base Rate & Per-Person Rate',
      description: 'Base Rate is the total billed for a 30-minute session. It scales with duration (60 min = 2x, 90 min = 3x). Per-Person Rate adds an extra charge per attendee for group services — leave at $0 for individual sessions.',
      element: '[data-tour="pricing-rates"]',
      popoverSide: 'bottom',
      ctaLabel: 'Next',
      href: '/settings/business/?tour=edit-service',
    },
    {
      title: 'Contractor Cap',
      description: 'Optional maximum a contractor can earn per session. Even if the pricing formula calculates more, their pay is capped here. Leave empty for no limit.',
      element: '#contractor_cap',
      popoverSide: 'bottom',
      ctaLabel: 'Next',
      href: '/settings/business/?tour=edit-service',
    },
    {
      title: 'Total Cap',
      description: 'Optional ceiling on the total amount billed per session, regardless of headcount. Useful for large groups so the bill doesn\'t get too high. Leave empty for no limit.',
      element: '#total_cap',
      popoverSide: 'bottom',
      ctaLabel: 'Next',
      href: '/settings/business/?tour=edit-service',
    },
    {
      title: 'Rent Percentage',
      description: 'Percentage of the session total withheld for facility rent. Typically 10% for Matt\'s Music. Set to 0% for in-home or other locations where no rent applies.',
      element: '#rent_percentage',
      popoverSide: 'bottom',
      ctaLabel: 'Next',
      href: '/settings/business/?tour=edit-service',
    },
    {
      title: 'Scholarship Rate',
      description: 'A flat dollar amount billed to the scholarship fund per session, regardless of duration. The contractor still gets their normal pay — the organization absorbs any difference. Leave empty if this isn\'t a scholarship service.',
      element: '#scholarship_rate',
      popoverSide: 'bottom',
      ctaLabel: 'Next',
      href: '/settings/business/?tour=edit-service',
    },
    {
      title: 'Contractor Pay by Duration',
      description: 'Set exact contractor pay amounts for each session length instead of calculating from MCA %. The "auto" value shows what the formula would give. Fill in only the durations you want to override. This is the most precise way to control contractor pay.',
      element: '[data-tour="pay-schedule"]',
      popoverSide: 'bottom',
      ctaLabel: 'Next',
      href: '/settings/business/?tour=edit-service',
    },
    {
      title: 'Scholarship Service Toggle',
      description: 'When on, sessions using this service type are batch-invoiced monthly on the Scholarship tab instead of generating individual invoices. Pair this with the Scholarship Rate above.',
      element: '#is_scholarship',
      popoverSide: 'bottom',
      ctaLabel: 'Next',
      href: '/settings/business/?tour=edit-service',
    },
    {
      title: 'Requires Client Toggle',
      description: 'Turn this off for admin work or tasks that don\'t involve a client. The session form will skip client and notes fields and instead ask "Who did this work?" showing only admin-role team members.',
      element: '#requires_client',
      popoverSide: 'bottom',
      ctaLabel: 'Next',
      href: '/settings/business/?tour=edit-service',
    },
    {
      title: 'Restrict to Contractors',
      description: 'Limit which team members can use this service type. Check the contractors who should have access. If none are checked, everyone can use it. Admins and owners always see all service types.',
      element: '[data-tour="contractor-restrictions"]',
      popoverSide: 'bottom',
      ctaLabel: 'Next',
      href: '/settings/business/?tour=edit-service',
    },
    {
      title: 'Active Toggle',
      description: 'Turn this off to hide the service type from the session form. Existing sessions are not affected. Use this to retire old service types without deleting them.',
      element: '#is_active',
      popoverSide: 'bottom',
      ctaLabel: 'Next',
      href: '/settings/business/?tour=edit-service',
    },
    {
      title: 'Save and Test',
      description: 'Click "Save Changes" to apply. Changes only affect new sessions — existing records stay the same. Use View As mode to confirm contractors see the right options. You can close the form now.',
      ctaLabel: 'Finish',
      href: '/settings/business/',
    },
  ],
}

export const ALL_WALKTHROUGHS: Walkthrough[] = [
  APP_OVERVIEW_WALKTHROUGH,
  ADD_CLIENT_WALKTHROUGH,
  LOG_SESSION_WALKTHROUGH,
  INVITE_CONTRACTOR_WALKTHROUGH,
  CONFIGURE_SERVICES_WALKTHROUGH,
  EDIT_SERVICE_TYPE_WALKTHROUGH,
  APPROVE_SESSIONS_WALKTHROUGH,
  SCHOLARSHIP_BILLING_WALKTHROUGH,
]

export function getWalkthroughById(id: string): Walkthrough | undefined {
  return ALL_WALKTHROUGHS.find(w => w.id === id)
}
