#!/usr/bin/env node
/**
 * Register (or remove) the dev portal as a Windows logon-startup app for the
 * current user — same HKCU Run-key pattern as the prod DB backup task.
 *
 *   node tools/dev-portal/install-startup.mjs            # install
 *   node tools/dev-portal/install-startup.mjs --remove   # uninstall
 *
 * Writes a hidden-window launcher (data/start-portal.vbs, machine-specific,
 * gitignored) that runs server.mjs with output appended to data/portal.log,
 * then points the HKCU Run key "MCADevPortal" at it.
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const DATA = join(HERE, 'data')
const VBS = join(DATA, 'start-portal.vbs')
const RUN_KEY = 'HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run'
const NAME = 'MCADevPortal'

if (process.argv.includes('--remove')) {
  execFileSync('reg', ['delete', RUN_KEY, '/v', NAME, '/f'], { stdio: 'inherit' })
  console.log('Removed startup entry', NAME)
  process.exit(0)
}

const node = process.execPath
const server = join(HERE, 'server.mjs')
const log = join(DATA, 'portal.log')

// VBS string literals escape " as "". The inner command is:
//   cmd /c ""<node>" "<server>" >> "<log>" 2>&1"
const cmd = `cmd /c ""${node}" "${server}" >> "${log}" 2>&1"`
const vbs = `' Auto-generated by install-startup.mjs — launches the MCA dev portal hidden at logon.\r\nSet WshShell = CreateObject("WScript.Shell")\r\nWshShell.Run "${cmd.replace(/"/g, '""')}", 0, False\r\n`

mkdirSync(DATA, { recursive: true })
writeFileSync(VBS, vbs)
execFileSync('reg', ['add', RUN_KEY, '/v', NAME, '/t', 'REG_SZ', '/d', `wscript.exe "${VBS}"`, '/f'], { stdio: 'inherit' })

console.log(`Installed: ${NAME} runs at logon via ${VBS}`)
console.log(`Portal will listen on http://localhost:4321 (log: ${log})`)
console.log('Remove any time with: node tools/dev-portal/install-startup.mjs --remove')
