/**
 * Capture production's schema. READ-ONLY — this is the only file that names
 * PROD_REF in a query path, and it constructs no write client.
 *
 * Produces, in E:/mtmdbback/cert-source/<stamp>/:
 *   prod-public-schema.sql   pg_dump --schema-only --schema=public
 *   prod-attachments.sql     cross-schema objects pg_dump -n public CANNOT restore
 *   capture-manifest.json    checksums + row counts, so a later step can prove
 *                            the capture is intact before dropping anything
 *
 * Why prod-attachments.sql exists: `DROP SCHEMA public CASCADE` also drops the
 * `on_auth_user_created` trigger (it lives on auth.users but calls a public
 * function) and the storage.objects RLS policies (they call public helpers).
 * `pg_dump --schema=public` restores the functions but not those attachments,
 * so signup would silently create auth users with no profile and uploads would
 * break. These are generated from pg_catalog, never hand-maintained.
 *
 * Usage:  node scripts/cert-refresh/capture-prod.mjs [--out <dir>]
 */
import './lib/run.mjs'
import { mkdirSync, writeFileSync, readFileSync, existsSync, statSync } from 'fs'
import { execFileSync } from 'child_process'
import { createHash } from 'crypto'
import { prodRead, envValue } from './lib/api.mjs'
import { PROD_REF, POOLER, PATHS } from './config.mjs'

const stamp = new Date().toISOString().replace(/[:T]/g, '-').slice(0, 16)
const outIdx = process.argv.indexOf('--out')
const outDir = outIdx >= 0 ? process.argv[outIdx + 1] : `${PATHS.captureRoot}/${stamp}`

mkdirSync(outDir, { recursive: true })
console.log(`Capturing prod ${PROD_REF} -> ${outDir}`)

// ---------------------------------------------------------------- schema dump
const pw = envValue('PROD_SUPABASE_DB_PASSWORD')
if (!pw) throw new Error('PROD_SUPABASE_DB_PASSWORD missing from .env.local')

const { host, port } = POOLER[PROD_REF]
const conn = `postgresql://postgres.${PROD_REF}@${host}:${port}/postgres`
const schemaFile = `${outDir}/prod-public-schema.sql`

console.log('  pg_dump --schema-only ...')
execFileSync(
  `${PATHS.pgBin}/pg_dump.exe`,
  // --no-privileges is required, not cosmetic: the pooler connects as `postgres`,
  // which on Supabase is not superuser and cannot execute the dump's
  // `ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin ...` lines. Grants are
  // re-applied explicitly by rebuild-schema.mjs instead.
  ['--schema-only', '--schema=public', '--no-owner', '--no-privileges', '--file', schemaFile, conn],
  { env: { ...process.env, PGPASSWORD: pw }, stdio: ['ignore', 'inherit', 'inherit'], timeout: 300_000 }
)

const schemaSql = readFileSync(schemaFile, 'utf8')
const tableCount = (schemaSql.match(/^CREATE TABLE /gm) || []).length
const fnCount = (schemaSql.match(/^CREATE FUNCTION |^CREATE OR REPLACE FUNCTION /gm) || []).length
if (tableCount < 10) {
  throw new Error(`Schema dump looks truncated: only ${tableCount} tables. Refusing to record it.`)
}
console.log(`  schema: ${tableCount} tables, ${fnCount} functions, ${statSync(schemaFile).size} bytes`)

// ----------------------------------------------------- cross-schema attachments
console.log('  capturing cross-schema attachments ...')

const triggers = await prodRead(`
  select format('DROP TRIGGER IF EXISTS %I ON %s; %s;', t.tgname, c.oid::regclass, pg_get_triggerdef(t.oid)) as stmt
  from pg_trigger t
  join pg_class c on c.oid = t.tgrelid
  join pg_namespace n on n.oid = c.relnamespace
  where not t.tgisinternal and n.nspname in ('auth','storage')
  order by 1
`)

const policies = await prodRead(`
  select format(
    'DROP POLICY IF EXISTS %I ON %I.%I; CREATE POLICY %I ON %I.%I AS %s FOR %s TO %s%s%s;',
    policyname, schemaname, tablename, policyname, schemaname, tablename,
    permissive, cmd, array_to_string(roles, ', '),
    coalesce(' USING (' || qual || ')', ''),
    coalesce(' WITH CHECK (' || with_check || ')', '')
  ) as stmt
  from pg_policies
  where schemaname <> 'public'
  order by schemaname, tablename, policyname
`)

const buckets = await prodRead(`
  select format(
    'INSERT INTO storage.buckets (id, name, public) VALUES (%L, %L, %L) ON CONFLICT (id) DO NOTHING;',
    id, name, public
  ) as stmt
  from storage.buckets order by id
`)

const attachments = [
  '-- Generated by scripts/cert-refresh/capture-prod.mjs — do not hand-edit.',
  '-- Cross-schema objects that DROP SCHEMA public CASCADE destroys and',
  '-- pg_dump --schema=public does not restore.',
  '',
  `-- triggers on auth.* / storage.* (${triggers.length})`,
  ...triggers.map((r) => r.stmt),
  '',
  `-- RLS policies outside public (${policies.length})`,
  ...policies.map((r) => r.stmt),
  '',
  `-- storage buckets (${buckets.length})`,
  ...buckets.map((r) => r.stmt),
  '',
].join('\n')

writeFileSync(`${outDir}/prod-attachments.sql`, attachments)
console.log(
  `  attachments: ${triggers.length} triggers, ${policies.length} policies, ${buckets.length} buckets`
)

if (triggers.length === 0) {
  console.warn('  WARNING: no auth/storage triggers found. Expected on_auth_user_created.')
}

// -------------------------------------------------------------- row + column census
const counts = await prodRead(`
  select relname as table, n_live_tup as approx_rows
  from pg_stat_user_tables
  where schemaname = 'public'
  order by relname
`)

const columns = await prodRead(`
  select table_name, string_agg(column_name, ',' order by ordinal_position) as cols
  from information_schema.columns
  where table_schema = 'public'
  group by table_name
  order by table_name
`)

const manifest = {
  prod_ref: PROD_REF,
  captured_at: new Date().toISOString(),
  pg_dump_version: execFileSync(`${PATHS.pgBin}/pg_dump.exe`, ['--version']).toString().trim(),
  pooler: { host, port },
  schema_file: 'prod-public-schema.sql',
  schema_sha256: createHash('sha256').update(schemaSql).digest('hex'),
  schema_bytes: Buffer.byteLength(schemaSql, 'utf8'),
  table_count: tableCount,
  function_count: fnCount,
  attachment_counts: {
    triggers: triggers.length,
    policies: policies.length,
    buckets: buckets.length,
  },
  approx_row_counts: Object.fromEntries(counts.map((r) => [r.table, Number(r.approx_rows)])),
  columns: Object.fromEntries(columns.map((r) => [r.table_name, r.cols.split(',')])),
}

writeFileSync(`${outDir}/capture-manifest.json`, JSON.stringify(manifest, null, 2))

console.log(`\nCapture complete: ${outDir}`)
console.log(`  sha256 ${manifest.schema_sha256.slice(0, 16)}...`)
console.log(`  ${Object.keys(manifest.columns).length} tables catalogued`)
if (!existsSync(`${outDir}/capture-manifest.json`)) throw new Error('manifest not written')
